# Shape
WIDTH = 800
HEIGHT = 600

# Colors
FUNCTION_COLOR = 0xe74c3c
GRID_COLOR = 0xecf0f1
HIGHLIGHTED_SQUARE_COLOR = 0xcccccc
HIGHLIGHTED_SQUARE_BACKGROUND_COLOR = 0xffffff
AXIS_COLOR = 0
BACKGROUND_COLOR = 0xa29bfe
PALETTE_COLOR = 0x2C3E50
